// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH3VpINuoWpXFqpiF6fVm2UL699whyIbc',
    appId: '1:955293055255:web:88f05c9b3485ef2b085f52',
    messagingSenderId: '955293055255',
    projectId: 'signin-app-7bef8',
    authDomain: 'signin-app-7bef8.firebaseapp.com',
    storageBucket: 'signin-app-7bef8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA6AcuvJpnOPhlWCQ4p-XTZWcgFXSDImg',
    appId: '1:955293055255:android:40d6dc3171ca7ff2085f52',
    messagingSenderId: '955293055255',
    projectId: 'signin-app-7bef8',
    storageBucket: 'signin-app-7bef8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfuvTySi5UUGTUUh6sgs_3Ts7tJ-m_PRk',
    appId: '1:955293055255:ios:2a7c64126bcd1a60085f52',
    messagingSenderId: '955293055255',
    projectId: 'signin-app-7bef8',
    storageBucket: 'signin-app-7bef8.appspot.com',
    androidClientId: '955293055255-v2g19c6hinnons0nld7i195p448tsa8m.apps.googleusercontent.com',
    iosClientId: '955293055255-aouni2ekqkaos838jv0muo0hp1173ogb.apps.googleusercontent.com',
    iosBundleId: 'com.jec.signinApp',
  );
}
